#!/usr/bin/env python3 

def main()
    user_name = input("What is users name?)
    print("hello", user_name)

    day_of_week = input("what day of the week is it?")
    print("Happy", day_of_week)

main()

